### PR TITLE
Upgrade to v1.8.0

### PR DESCRIPTION
**Pull request by parkske**
* Merge main at v1.8.0 into runtimecore branch.
* Update lua build file to accommodate updates.
* Update conan file with new version information.

3rdparty vTest: https://runtime-rtc.esri.com/view/vTest/job/vtest/job/3rdparty-interface/427/downstreambuildview/
Downstream RTC vTest: https://runtime-rtc.esri.com/view/vTest/job/vtest/job/runtimecore-interface/9622/downstreambuildview/

### CODE REVIEW

**Comment by parkske** [comment]
From https://github.com/Esri/benchmark/pull/4/commits/5ff971149c2dc1f717f1cd3e5d44ba1cadfd23bc on are the commits of interest.

**Comment by parkske** [comment]
Something still isn't right on Windows. I need to address that first.

**Comment by parkske** [comment]
> Something still isn't right on Windows. I need to address that first.

Addressed. Should be good now.

**Review by Craig-Proctor — APPROVED** [review]

**Review by cfrankmiller — APPROVED** [review]

**Comment by parkske** [comment]
RTC branch consuming this if you're interested: https://devtopia.esri.com/runtime/runtimecore/pull/23363

**Review by john4744 — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by colingpowell — APPROVED** [review]

**Pull request merged**
